"""
Every generator registers itself here by decorator, and `to_json()` is what
becomes art/generators/registry.json -- the file spec-validate reads and the
one generators.md is written from. A test regenerates both and fails on a
diff, so the Python surface, the JSON and the docs cannot drift.

Importing the sub-packages is what populates the tables; `load_all()` does
that on demand so the pure modules stay importable on their own.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

from . import palette
from .params import P


@dataclass
class BodyPlanDef:
    name: str
    cls: str  # creep | tower | projectile | tile | prop | any
    params: dict[str, P]
    attachments: list[str]
    slots: list[str]
    doc: str
    fn: Callable  # (params: dict, rng) -> Layout


@dataclass
class PartDef:
    name: str
    attaches: list[str]
    default_at: str
    slots: list[str]
    doc: str
    fn: Callable  # (size: float, rng) -> Layout, in the attachment's local frame
    triangles: int = 0


@dataclass
class RigDef:
    name: str
    plans: list[str]
    bones: list[str]
    ik: list[str]
    doc: str
    fn: Callable  # (layout: Layout) -> list[Bone]


@dataclass
class AnimDef:
    name: str
    clips: list[str]
    loop: bool
    params: dict[str, P]
    doc: str
    fn: Callable  # (params, rig_bones, fps, rng) -> Clip


@dataclass
class Registry:
    body_plans: dict[str, BodyPlanDef] = field(default_factory=dict)
    parts: dict[str, PartDef] = field(default_factory=dict)
    rigs: dict[str, RigDef] = field(default_factory=dict)
    animations: dict[str, AnimDef] = field(default_factory=dict)


REG = Registry()


def body_plan(name: str, cls: str, params: dict[str, P], attachments: list[str], slots: list[str], doc: str):
    def deco(fn):
        REG.body_plans[name] = BodyPlanDef(name, cls, params, attachments, slots, doc.strip(), fn)
        return fn

    return deco


def part(name: str, attaches: list[str], default_at: str, slots: list[str], doc: str, triangles: int = 0):
    def deco(fn):
        REG.parts[name] = PartDef(name, attaches, default_at, slots, doc.strip(), fn, triangles)
        return fn

    return deco


def rig(name: str, plans: list[str], bones: list[str], ik: list[str], doc: str):
    def deco(fn):
        REG.rigs[name] = RigDef(name, plans, bones, ik, doc.strip(), fn)
        return fn

    return deco


def animation(name: str, clips: list[str], loop: bool, params: dict[str, P], doc: str):
    def deco(fn):
        REG.animations[name] = AnimDef(name, clips, loop, params, doc.strip(), fn)
        return fn

    return deco


_loaded = False


def load_all() -> Registry:
    global _loaded
    if not _loaded:
        from . import plans, parts, rigs, anims  # noqa: F401  (registration side effects)

        _loaded = True
    return REG


def to_json() -> dict:
    from . import GENERATOR_VERSION

    r = load_all()
    return {
        "_comment": "GENERATED by `python3 -m ltw_art.registry` from art/generators/ltw_art. Do not edit. spec-validate reads this; generators.md is written from the same tables.",
        "version": GENERATOR_VERSION,
        "palette": dict(palette.COLOURS),
        "palette_aliases": dict(palette.ALIASES),
        "body_plans": {
            **{
                n: {"class": d.cls, "attachments": d.attachments, "slots": d.slots, "params": {k: p.to_json() for k, p in d.params.items()}, "doc": d.doc}
                for n, d in sorted(r.body_plans.items())
            },
            # Not a generator: the import path (bl/importer.py) handles it, but
            # spec-validate needs the name to exist and accept any class.
            "imported": {"class": "any", "attachments": [], "slots": [], "params": {}, "doc": "An external model brought to the conventions by the import path. Parameters live under `import:`."},
        },
        "parts": {
            n: {"attaches": d.attaches, "default_at": d.default_at, "slots": d.slots, "triangles": d.triangles, "doc": d.doc}
            for n, d in sorted(r.parts.items())
        },
        "rigs": {n: {"plans": d.plans, "bones": d.bones, "ik": d.ik, "doc": d.doc} for n, d in sorted(r.rigs.items())},
        "animations": {
            n: {"clips": d.clips, "loop": d.loop, "params": {k: p.to_json() for k, p in d.params.items()}, "doc": d.doc}
            for n, d in sorted(r.animations.items())
        },
    }


if __name__ == "__main__":
    # Running as `python3 -m ltw_art.registry` executes this file as
    # __main__, a second copy of the module whose REG the plans never
    # register into. Delegate to the real one.
    import json
    import sys

    from ltw_art.registry import to_json as real_to_json

    json.dump(real_to_json(), sys.stdout, indent=2)
    print()
